package category_controller

import (
	"net/http"

	"github.com/Modeva-Ecommerce/modeva-cms-backend/config"
	"github.com/Modeva-Ecommerce/modeva-cms-backend/models"
	"github.com/gin-gonic/gin"
	"gorm.io/gorm"
)

// CreateCategory godoc
// @Summary Create a new category or subcategory
// @Description Add a new category (parentId optional — if provided, this becomes a subcategory)
// @Tags CMS - Categories
// @Accept json
// @Produce json
// @Param category body models.CategoryRequest true "Category input"
// @Success 201 {object} models.ApiResponse
// @Failure 400 {object} models.ApiResponse
// @Router /api/v1/admin/categories [post]
func CreateCategory(c *gin.Context) {
	var input models.CategoryRequest

	// Step 1: Validate JSON input
	if err := c.ShouldBindJSON(&input); err != nil {
		c.JSON(http.StatusBadRequest, models.ErrorResponse(c, err.Error()))
		return
	}

	// Step 2: If parentId provided, validate it
	var parentName *string
	if input.ParentID != nil {
		var parent models.Category

		// Find parent category by ID
		result := config.CmsGorm.First(&parent, "id = ?", *input.ParentID)

		// Check if parent exists
		if result.Error != nil {
			if result.Error == gorm.ErrRecordNotFound {
				c.JSON(http.StatusBadRequest, models.ErrorResponse(c, "Invalid parentId: category not found"))
			} else {
				c.JSON(http.StatusInternalServerError, models.ErrorResponse(c, "Database error"))
			}
			return
		}

		// Step 3: Prevent nesting deeper than 1 level
		if parent.ParentID != nil {
			c.JSON(http.StatusBadRequest, models.ErrorResponse(c, "Subcategories cannot have their own parent"))
			return
		}

		parentName = &parent.Name
	}

	// Step 4: Create the category object
	category := models.Category{
		Name:        input.Name,
		Description: input.Description,
		Status:      "Inactive", // Default status
		ParentID:    input.ParentID,
		ParentName:  parentName,
		// ID will be auto-generated by BeforeCreate hook
	}

	// Step 5: Save to database
	if err := config.CmsGorm.Create(&category).Error; err != nil {
		c.JSON(http.StatusInternalServerError, models.ErrorResponse(c, "Failed to create category"))
		return
	}

	// Step 6: Transform to CategoryWithProducts (products = 0 for new category)
	response := models.CategoryWithProducts{
		ID:          category.ID,
		Name:        category.Name,
		Description: category.Description,
		Status:      category.Status,
		ParentID:    category.ParentID,
		ParentName:  category.ParentName,
		CreatedAt:   category.CreatedAt,
		UpdatedAt:   category.UpdatedAt,
		Products:    0, // New category has no products yet
	}

	// Step 7: Return success response
	c.JSON(http.StatusCreated, models.SuccessResponse(c, "Category created", response))
}
